name: Build Unsigned IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"

      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Get Dependencies
        working-directory: budget
        run: flutter pub get

      - name: Clean
        working-directory: budget
        run: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock

      - name: Install Pods
        working-directory: budget/ios
        run: |
          pod repo update
          pod install

      - name: Build Unsigned IPA
        working-directory: budget
        run: |
          flutter build ipa \
            --release \
            --no-codesign

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: budget/build/ios/ipa/*.ipa
